### ISSUE TITLE
This repository should be renamed to a herb name?

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/herbsshelf#1]
Just a generic question, about whether this repository should also be an herb, since the intention is to evolve it into something bigger (playground for example)

**Comment by endersoncosta** [comment]
I believe in that, or something like herbs2docs

**Comment by m7vicente-vortx** [comment]
Once 'self' its more like a new form of 'swagger', they could be called something different but evolving and herb, like an 'garden', 'herbage' or 'greenHouse'.

**Comment by BritoDoug** [comment]
Has this discussion ended?

**Comment by jhomarolo** [comment]
I believe not, I imagine that we still need to reach a consensus

**Comment by italojs** [comment]
herbs2docs is awesome, is auto explainable

**Comment by italojs** [comment]
@jhomarolo so?
