### ISSUE TITLE
Link to Herbs project

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsshelf#18]
![image](https://user-images.githubusercontent.com/209287/134828752-3923ccc8-12ba-47db-89f8-7c9fb1279bd7.png)

The shelf page is all about the project domain / documentation. We should have little to no distraction like Herbs links.

1. It is unnecessary to have "Contribute on Github" that big on the screen. I think it should not be here at all.

2. The Herbs logo can / should have a link to Herbs' github page

**Comment by vxksf** [comment]
I just opened a PR with an implementation for this issue. Here the link: https://github.com/herbsjs/herbsshelf/pull/23
