### ISSUE TITLE
Icons now showing up

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/herbsshelf#20]
**Describe the bug**
The icons in the menu bar are not loading correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/6617759/135676212-0e39d30c-e675-42f3-baea-08f0aa47fecb.png)

**Comment by vxksf** [comment]
Sorry, i'm a little confuse about how that icon should be. Could you give more informations about?

**Comment by jhomarolo** [comment]
@vxksf it seems the icons are not loading correctly

**Comment by juliadibo** [comment]
The icons are being loaded correctly, that is the right icon, as you can see in the prototype.

![image](https://user-images.githubusercontent.com/68744518/149625754-fb1d895c-b74d-479a-875f-f7ed8fdab64f.png)
