### ISSUE TITLE
A place to find all my Shelf's

### ISSUE THREAD

**Issue by leohirano** [herbsjs/herbsshelf#21]
Today is hard to find all my Shelf's to share with my team, when I need to consult a Shelf I go to Slack and use the find every time.

Could have a place to concentrate the path to all my Shelf's, it would be much easier to find my documentation.

Like a Shelf made from Shelf's.

**Comment by italojs** [comment]
I think It's isn't herbsjs's resposability, you need to organize it your self in your company/team/group
