### ISSUE TITLE
Icons in dark mode

### ISSUE THREAD

**Issue by ghost** [herbsjs/herbsshelf#22]
**Describe the bug**
Icons in Step, Request and Response are not visible in dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/84990821/139126762-c4e45ca7-066f-47ce-a013-c2d980edd2c3.png)

![image](https://user-images.githubusercontent.com/84990821/139126649-828ea862-24b6-47c6-96bf-1037b00853c8.png)

**Comment by juliadibo** [comment]
I´m going to fix it.
