### ISSUE TITLE
Herbarium - Use it for discovery

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsshelf#25]
With the new release of [Herbarium](https://github.com/herbsjs/herbarium), Herbs Shelf can generate docs using it.

Instead of custom files (ex: `_uclist.js`), using Herbarium will be much simpler since it is a standardized way to access Herbs objects.

ex: `renderHTML("My Project", herbarium)` where `herbarium` constains all Herbs objects and its metadatas.

It is also an oportunity to include on the doc other objects like Entities (https://github.com/herbsjs/herbsshelf/issues/24) and Repositories.

**Comment by italojs** [comment]
do you think herbrarium is already done for use it into production/others libs? I think it still in beta

**Comment by dalssoft** [comment]
> I think it still in beta

We still have to use it in heavy production system and check, but in terms for features is pretty much ok to use.

Regardless its stability Herbarium is the way to go extract metadata from a project, so this issue is important since Shelf will have a standard way to consume the metadata in the future (very soon).

**Comment by italojs** [comment]
ok, my unique point is to have maintain it updated since we will have many changes into the herbarium, but we could to implement it, i agree

**Comment by dalssoft** [comment]
The last herbsshelf version added this feature. Closing the issue.
