### ISSUE TITLE
Use case visualization with Mermaid.js

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsshelf#37]
It would be interesting to understand a use case not only in code but also having a more "visual" approach and have this information as part of Shelf experience.

For that we could extract metadata from Herbs `usecase` and export to MermaidJS:

```
graph TD
    A([Update User Account])
    B(Validate given User Account information)
    C(Is User expired?)
    D{If User is expired}
    E(Then Activate User)
    F(Else Do nothing)
    G(Save User Account)
    A --> B
    B --> C
    C --> D
    D --> E
    D --> F
    E --> G
    F --> G
```

Generated graph (by github / mermaid):
```mermaid
graph TD
    A([Update User Account])
    B(Validate given User Account information)
    C(Is User expired?)
    D{If User is expired}
    E(Then Activate User)
    F(Else Do nothing)
    G(Save User Account)
    A --> B
    B --> C
    C --> D
    D --> E
    D --> F
    E --> G
    F --> G
```

**Comment by maikvortx** [comment]
Guys, where do you think this diagram should be on the shelf? I think to put it on the bottom of usecase details. 



![Image](https://user-images.githubusercontent.com/65735194/177452524-d23cafb6-1e1d-4a69-99f0-d73444b8e09f.png)

**Comment by dalssoft** [comment]
My suggestion is to have a switch buttons to view steps as text or as workflow, something like this:

![image](https://user-images.githubusercontent.com/209287/177544631-f17dd753-6688-4354-8c86-604f35005ffa.png)

**Comment by maikmb** [comment]
Hello! What do you think about this example? 

![screenshot-localhost_4000-2022 07 18-18_57_28](https://user-images.githubusercontent.com/4916896/179624530-e17dab28-792f-42fa-be57-a3177b14be46.png)

![screenshot-localhost_4000-2022 07 18-18_55_45](https://user-images.githubusercontent.com/4916896/179624532-4d754ab2-e0ba-4047-815b-52bdf76fad39.png)

**Comment by dalssoft** [comment]
Wow! great job @maikmb!

(1) is it possible to change the color of the graph? this blue/purple doesn't match the current visual identity.

(2) have you tested with complex UCs (many IFs and/or multi-level steps)?

**Comment by jhomarolo** [comment]
Well done @maikmb!

For me, we just need to change the colors, nothing more.

**Comment by maikmb** [comment]
Hey guys! 

This is an example with Herbs primary color and complex UCs like many Ifs or multi-level-steps. Any more suggestions? 

![screenshot-localhost_4000-2022 07 24-21_13_37](https://user-images.githubusercontent.com/4916896/180671953-578f977f-9331-4fc8-b0c1-11d3398fff05.png)

**Comment by jhomarolo** [comment]
Awesome!

**Comment by jhomarolo** [comment]
Please open the PR

**Comment by dalssoft** [comment]
Wow! its getting very cool!!

One thing that I didn't understand was this part:
![image](https://user-images.githubusercontent.com/209287/180675934-6b32dada-3d5e-463d-bdf9-16eecb787252.png)

Could you post here the code for this use case?

**Comment by maikvortx** [comment]
> Please open the PR

Hi @jhomarolo, I will implement unit tests to open PR. I need one more day to implement it.

**Comment by maikmb** [comment]
> Wow! its getting very cool!!
> 
> One thing that I didn't understand was this part: ![image](https://user-images.githubusercontent.com/209287/180675934-6b32dada-3d5e-463d-bdf9-16eecb787252.png)
> 
> Could you post here the code for this use case?

Hi @dalssoft ! This part refers to Multi Level Steps. 

![image](https://user-images.githubusercontent.com/4916896/180813758-cb5fc23c-35e1-4281-8425-724093e2b418.png)

**Comment by maikmb** [comment]
Hey guys, here's the full example with complex Multi-Level Steps. 

Flow Chart

![screenshot-localhost_4000-2022 07 26-22_32_40](https://user-images.githubusercontent.com/4916896/181141277-a79dfad6-5f9c-4b83-b9b0-6aa915dd400a.png)

Usecase

```
const updateItem = (injection) =>
  usecase('Update Item', {
    request: {
      id: Number,
      description: String,
      isDone: Boolean,
      position: Number
    },

    response: Item,

    'Validate request': step(async (ctx) => {
      return Ok()
    }),

    'Check if is necessary to update': ifElse({
      'If position has changed ': step((ctx) => {
        return Ok(true)
      }),

      'Save itens': step(async (ctx) => {
        return Ok()
      }),

      'Updated item': step(async (ctx) => {
        return Ok()
      }),
    }),

    'Notify update item': step(async (ctx) => {
      return Ok()
    }),

    'Calculate stock': step(async (ctx) => {
      return Ok()
    }),

    'Send real time events': step({

      'Update mobile push notifications': step(async (ctx) => {
        return Ok()
      }),

      'Update payment cart': step(async (ctx) => {
        return Ok()
      }),     

    }),

    'Check if has product': ifElse({
      'If has product ': step((ctx) => {
        return Ok(true)
      }),

      'Update product item': step(async (ctx) => {
       return Ok()
      }),

      'Create product item': step(async (ctx) => {
        return Ok() 
      }),
     
    }), 

    'Update cart dashboard': step(async (ctx) => {
      return Ok()
    }),
    
    'Save product': step({

      'Update database': step(async (ctx) => {
        return Ok()
      }),

      'Update cache database': step(async (ctx) => {
        return Ok()
      }),     

    }),

  })


```

**Comment by dalssoft** [comment]
Is there a PR for this issue? I couldn't find.

**Comment by maikvortx** [comment]
Hi @dalssoft,

I will open a PR for this feature. I created a new glue, herbs2mermaid, and configure it for my project to test with shelf.

**Comment by jhomarolo** [comment]
@maikmb when you finish, please put the pr link here

**Comment by dalssoft** [comment]
since we have https://github.com/herbsjs/herbs2mermaid now, can we move on with this feature?
