### ISSUE TITLE
Entities visualization with Mermaid.js 

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsshelf#38]
It would be interesting to understand a entity and its relationships not only in code but also having a more "visual" approach and have this information as part of Shelf experience.

For that we could extract metadata from Herbs `entity` and export to MermaidJS:

```
classDiagram
    class User {
        Number ID
        String firstName
        String lastName
        Number age
        User_Account[] accounts
    }
    class User_Account{
        Number ID
        Date expirationDate
        isExpired()
    }
    class Project{
        Number ID
        String name
        User_Account user
        Task[] tasks
    }
    class Task{
        Number ID
        String name
        Date dueDate
    }
    User "1" --> "*" User_Account
    Project "1" --> "1" User_Account
    Project "1" --> "*" Task
```

```mermaid
classDiagram
    class User {
        Number ID
        String firstName
        String lastName
        Number age
        User_Account[] accounts
    }
    class User_Account{
        Number ID
        Date expirationDate
        isExpired()
    }
    class Project{
        Number ID
        String name
        User_Account user
        Task[] tasks
    }
    class Task{
        Number ID
        String name
        Date dueDate
    }
    User "1" --> "*" User_Account
    Project "1" --> "1" User_Account
    Project "1" --> "*" Task
```

**Comment by italojs** [comment]
why did you reopen it? 
If you reopen it becase we need to improve the current implementation, you could to open another issue, becase the #41 PR already fix this current issue

**Comment by dalssoft** [comment]
> becase the https://github.com/herbsjs/herbsshelf/pull/41 PR already fix this current issue

well, not really. the initial idea was to have this diagrams inside Shelf UI with diagrams auto generated by Herbs metadata. The PR above only allows to Mermaid diagrams to be part of the README file, created manually (which is completely fine).

**Comment by jhomarolo** [comment]
@dalssoft is right. I reopened it because is not totally closed yet.

**Comment by maikvortx** [comment]
Hi guys! I will work on this issue!

**Comment by maikvortx** [comment]
Hey guys. Any suggestion? I'm working on this feature and just missing details to complete it.

![image](https://user-images.githubusercontent.com/65735194/176255590-ddeee5d2-8f78-433a-8e07-934c57131abd.png)

**Comment by dalssoft** [comment]
@maikmb ideally we could have a more in-depth discussion on how to document the entities, but thinking about it, I believe your suggestion would work well for a first version

**Comment by maikvortx** [comment]
Thanks @dalssoft! We will implement the first version and improve it later.

**Comment by jhomarolo** [comment]
Maik, I believe the diagram connection (1 ... N ) in the image is missing, right?

Like this:

![image](https://user-images.githubusercontent.com/6617759/176260621-ce99a26e-4d8c-493a-aeff-5dac772393d0.png)

**Comment by maikvortx** [comment]
Hi @jhomarolo!
I was implementing this feature. 

![image](https://user-images.githubusercontent.com/65735194/176325618-439cae37-bf8a-478f-9188-efb1f50cbbb0.png)

**Comment by dalssoft** [comment]
Related: https://github.com/herbsjs/herbsshelf/issues/24

**Comment by maikvortx** [comment]
Hi everyone! 
@jhomarolo The relationship is created automatically by herbsshelf. 

![image](https://user-images.githubusercontent.com/65735194/176982772-0798eed2-6950-4129-98ad-12ca405be70a.png)

**Comment by maikvortx** [comment]
Hey  guys, I have implemented the new version of the herbs shelf in internal project and I have an example of a complex entities class diagram: 

![image](https://user-images.githubusercontent.com/65735194/177240615-30d22b1e-878e-422c-9491-6312f5fc2ee3.png)

![image](https://user-images.githubusercontent.com/65735194/177240620-e9e40424-3f2d-4d67-8a7a-25d048c15bd0.png)

**Comment by jhomarolo** [comment]
@maikvortx, It's becoming excellent! I have only two considerations:

1 - About the ordering of the diagram. Is there any way to sort the diagram automatically? It seemed to me that the diagram gets a little confusing in a big setting

2 - I believe that mine needs to include use cases and entities. That is, create a folder called use cases and leave them there. From the way you sent the print, it implies that the entities link is also a use case

Does it make sense to you? I think we're almost there on this PR!

**Comment by dalssoft** [comment]
@maikmb amazing work! this is going to be a killer feature!

I agree with @jhomarolo on (1): i think we should find a way to implement a diagram reorder. ideally having a button where the user can choose which reorder they want. regarding (2) (to include use cases and entities), i think it is a improvement we can discuss, but for now I would leave without UCs.

**Comment by maikmb** [comment]
Hey guys! I agree with you.

(1) What do think about implementing diagram reorder in another PR? I will study Mermaid to implement this feature. In a big project, the class diagram gets a little confusing. 
(2) About usecases, I will implement this in another PR for this issue #37

**Comment by dalssoft** [comment]
> I will study Mermaid to implement this feature. In a big project, the class diagram gets a little confusing.

"de bate pronto", is there a any indication of Mermaid having this feature? It doesn't seem like it https://github.com/mermaid-js/mermaid/issues/806

**Comment by dalssoft** [comment]
> I have an example of a complex entities class diagram https://github.com/herbsjs/herbsshelf/issues/38#issuecomment-1174549539

We could use groups metadata to entities like we have in use cases. This way we could create sub-views to view entities so we don´t have to show the whole thing... yes, I know, it is another issue, but just to document it

**Comment by maikmb** [comment]
> > I have an example of a complex entities class diagram https://github.com/herbsjs/herbsshelf/issues/38#issuecomment-1174549539
> 
> We could use groups metadata to entities as we have in use cases. This way we could create sub-views to view entities so we don´t have to show the whole thing... yes, I know, it is another issue, but just to document it

It's a good idea @dalssoft. I can implement it in another PR.

**Comment by maikmb** [comment]
> @maikmb It seems we have many ideas for improvements here. But what is missing to accept this PR? https://github.com/herbsjs/herbsshelf/pull/47

@dalssoft I think this PR can be approved. The improvements discussed here will be implemented separated.

**Comment by maikmb** [comment]
Hey guys! What you think about this layout: 

![Entities Group Diagram](https://user-images.githubusercontent.com/4916896/177453650-ad822338-2e9e-4376-8b4d-8c446d31a16a.jpg)

![screenshot-localhost_4000-2022 07 05-23_02_12](https://user-images.githubusercontent.com/4916896/177453783-69679ec7-49df-410f-bbf0-05a6543124e8.png)


- Group entities
- Group Usecases
- Include usecase workflow at the bottom of the details

**Comment by dalssoft** [comment]
> Group entities

Great!!! But in order to have groups shown, it must be informed as metadata:

```js
module.exports =
  herbarium.entities
    .add(List, 'List')
    .metadata({ group: 'Core Entities' })
    .entity
```
