### ISSUE TITLE
Shelf UI improvements

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbsshelf#43]
UI improvements:

![image](https://user-images.githubusercontent.com/209287/171680156-a0302cd1-b5d2-4a49-a8fe-2036163dc459.png)

https://www.figma.com/file/VHpB9XdDTndsjR6lf7VcHo/HerbsJS?node-id=408%3A2

**Comment by italojs** [comment]
this issue could have a `good4beginners` tag

**Comment by juliadibo** [comment]
I can do this. I will send the PR this week.

**Comment by dalssoft** [comment]
@juliadibo can we close this issue?

**Comment by dalssoft** [comment]
Great! thank you @juliadibo !
